name: Update generalsports.m3u

on:
  schedule:
    - cron: "*/30 * * * *"  # Her 30 dakikada bir çalışır
  workflow_dispatch:       # Manuel tetiklemeye de izin verir

jobs:
  update-generalsports:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPO: a7shk1/m3u-broadcast
      GITHUB_BRANCH: main
      DEST_REPO_PATH: generalsports.m3u
      COMMIT_MESSAGE: "chore: auto-update sports channels from daddylive"
      SOURCE_URL: https://raw.githubusercontent.com/DisabledAbel/daddylivehd-m3u/f582ae100c91adf8c8db905a8f97beb42f369a0b/daddylive-events.m3u8
      DEST_RAW_URL: https://raw.githubusercontent.com/a7shk1/m3u-broadcast/main/generalsports.m3u

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to update M3U
        run: python scripts/pull_match_football_from_daddylive.py
